config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :comments

  resources :submits

  resources :users

  root :to => redirect('/submits?submit_type=new')

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get '/submits/upvote/:id', to: 'submits#upvote'
  get '/comments/upvote/:id', to: 'comments#upvote'
  get '/comments/new/:submit_id', to: 'comments#new'
  get '/comments/new/:submit_id/:parent_id', to: 'comments#new'
end

app/models/submit.rb
class Submit < ActiveRecord::Base
	#attr_accessible :submit_type, :url
	acts_as_votable
	belongs_to :user
	has_many :comments
	
	default_scope -> { order(created_at: :desc) }
	
	validates :title, presence: true

	validates :url, presence: true, if: :news
	validates :url, absence: true, if: :questions
    def news
    	submit_type == "new"
    end
    def questions
    	submit_type == "question"
    end

	#validates :url, format: { with: /\A#{URI::regexp}\z/,
    #message: "Please insert a valid URL" }

    #include ActiveModel::Validations
  	#validates_with SubmitValidator
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_submit, only: [:show, :edit, :update, :destroy]

  # GET /submits
  # GET /submits.json
  def index
    if params[:submit_type]
      @submits = Submit.where("submit_type = ?", params[:submit_type])
    else
      @submits = Submit.all
    end


  end

  # GET /submits/1
  # GET /submits/1.json
  def show
  end

  # GET /submits/new
  def new
    @submit = Submit.new
  end

  # GET /submits/1/edit
  def edit
  end

  # POST /submits
  # POST /submits.json
  def create
    # MODIFY RUBY HASH IN PLACE
    # Option 1 straight-forward (check out submit_params method)
    # sp = submit_params
    # sp[:user_id] = 1
    # @submit = Submit.new(sp)

    # Option 2 simpler (check out submit_params method)
    if current_user
      submit_params[:user_id] = current_user.user_id
    end

    submit_params[:score] = 0
    if submit_params[:submit_type] == 'question'
      submit_params[:url] = nil
    end

    @submit = Submit.new(submit_params)

    respond_to do |format|
      if @submit.save
        format.html { redirect_to @submit, notice: 'Submit was successfully created.' }
        format.json { render :show, status: :created, location: @submit }
      else
        format.html { render :new }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submits/1
  # PATCH/PUT /submits/1.json
  def update
    respond_to do |format|
      if @submit.update(submit_params)
        format.html { redirect_to @submit, notice: 'Submit was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit }
      else
        format.html { render :edit }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submits/1
  # DELETE /submits/1.json
  def destroy
    @submit.destroy
    respond_to do |format|
      format.html { redirect_to submits_url, notice: 'Submit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /submits/upvote/1
  # GET /submits/upvote/1.json
  def upvote
    @submit = Submit.find(params[:id])
    if current_user
      if not current_user.voted_for? @submit
         current_user.up_votes @submit
         Submit.increment_counter(:score, params[:id])
      end
      respond_to do |format|
        format.html { redirect_to '/' }
        format.json { render :show, status: :created, location: @submit }
      end
    else
      respond_to do |format|
        format.html {redirect_to submits_path+'?submit_type=new', alert: "Log in for voting the news." }
        format.json {render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submit
      @submit = Submit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submit_params
      # Option 1 straight-forward (check out create method)
      # params.require(:submit).permit(:title, :score, :url, :submit_type, :user_id)

      # Option 2 simpler (check out create method)
      @submit_params ||= params.require(:submit).permit(:title, :score, :url, :submit_type, :user_id)
    end
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/submits/_form.html.erb
<%= form_for(@submit) do |f| %>
  <% if @submit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit.errors.count, "error") %> prohibited this submit from being saved:</h2>

      <ul>
      <% @submit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :submit_type %><br>
    <%= f.select :submit_type, options_for_select(%w[new question]) %>
  </div>
  <div class="field" id="submit_url_field">
    <%= f.label :url %><br>
    <%= f.url_field(:url) %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>

  <script type="text/javascript">
      $("#submit_submit_type").change(function() {
        $("#submit_url_field").toggle();
    });
  </script>

<% end %>

app/views/submits/edit.html.erb
<h1>Editing submit</h1>

<%= render 'form' %>

<%= link_to 'Show', @submit %> |
<%= link_to 'Back', submits_path %>

app/views/submits/index.html.erb
<div style="width:800px; margin:0 auto;">
  <%= link_to 'New Submit', new_submit_path %>
</div>

<table>
  <tbody>
    <% @submits.each do |submit| %>
      <% if submit.submit_type == params[:submit_type] %>
        <tr>
          <td class='itemTitle'>
            <% if submit.url %>
              <%= link_to submit.title, URI.encode(submit.url) %>
              <% @uri = URI.parse(submit.url)%>
              <% if @uri.host %><%= "(" + @uri.host + ")" %><% end %>
            <% else %>
              <%= submit.title %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td class='itemInfo'>
          <%= link_to(image_tag("up.png", :height => 15, :width => 15), '/submits/upvote/'+String(submit.id)) %>
          <%= submit.score %> points by <%= link_to submit.user.name, submit.user %> <%= time_ago_in_words(submit.created_at) %> ago | <%= submit.comments.length %> <%= link_to 'comments', submit %></td>
        </tr>
        <% if current_user %>
          <% if current_user.user.id == submit.user.id %>
            <tr> 
              <td><%= link_to 'Edit', edit_submit_path(submit) %></td>
             <td><%= link_to 'Destroy', submit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/submits/new.html.erb
<h1 class="strongBody" >New submit</h1>

<% if current_user %>
	<%= render 'form' %>
<% else %>
	<p>Please, log in to create a new submission.</p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/submits/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
      <tr>
        <td class='itemTitle'>
          <% if @submit.url %>
            <%= link_to @submit.title, URI.encode(@submit.url) %> (<%= URI.join(@submit.url).to_s %>)</td>
          <% else %>
            <%= @submit.title %>
          <% end %>
      </tr>
      <tr>
        <td class='itemInfo'><%= @submit.score %> points by <%= @submit.user.name %> <%= time_ago_in_words(@submit.created_at) %> ago</td>
        <td>(<%= @submit.submit_type %>)</td>
      </tr>

      <tr>
        <td><%= link_to 'Edit', edit_submit_path(@submit) %></td>
        <td><%= link_to 'Destroy', @submit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

  </tbody>
</table>

<%= link_to 'Edit', edit_submit_path(@submit) %> |
<%= link_to 'Back', submits_path+'?submit_type=new' %>


<h3 class="strongBody">Comments: </h3>
<%= link_to 'New comment', '/comments/new/'+String(@submit.id) %>
<ul>
    <% @submit.comments.each do |comment| %>

      <%if comment.parent_id.nil? %>
        <li><p>
        <%= link_to '[+]', '/comments/upvote/'+String(comment.id) %>
        <%= comment.score %> points by
        <%= link_to comment.user.name, comment.user %> |
        <%= time_ago_in_words(comment.created_at) %> |
        <%= link_to 'reply', '/comments/new/'+String(@submit.id)+'/'+String(comment.id) %>
      </p></li>
      <p>
        <%= comment.content %>
      </p>
      <% @submit.comments.each do |reply| %>
        <%if reply.parent_id == comment.id%>
          <blockquote><li type='circle'>
          <%= link_to '[+]', '/comments/upvote/'+String(reply.id) %>
          <%= reply.score %> points by
          <%= link_to reply.user.name, reply.user %> |
          <%= time_ago_in_words(reply.created_at) %> |
        </li></blockquote>
        <blockquote>
          <%= reply.content %>
        </blockquote>
        <%end%>
        <%end%>
      <%end%>
    <% end %>
</ul>