config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :comments

  resources :submits

  resources :users

  root :to => redirect('/submits?submit_type=new')

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get '/submits/upvote/:id', to: 'submits#upvote'
  get '/comments/upvote/:id', to: 'comments#upvote'
  get '/comments/new/:submit_id', to: 'comments#new'
  get '/comments/new/:submit_id/:parent_id', to: 'comments#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facker News</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id='webHeader'>
		<img src=<%= asset_path('original.png') %>/><h1 class="headerLink"><%= link_to 'Facker News', root_url %></h1>
    <div id='sign_out' class="headerLink">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong> !
	<div id="editLogout"><div class="headerLink" id='a1'>
		<%=link_to "Sign out", signout_path%>
    	</div>
	<div class="headerLink" id="hp2">   <%=link_to 'Edit profile', edit_user_path(current_user.user) %></div>
</div>
      <% else %>
        <a class="headerLink" href="/auth/google_oauth2">
		<img id='googlesign'src=<%= asset_path('google.png') %>/>
        </a>
      <% end %>
    </div>
    <div class="headerLink"><%= link_to 'News', submits_path+'?submit_type=new'%></div>
    <div class="headerLink"><%= link_to 'Questions', submits_path+'?submit_type=question'%></div>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  
<%= yield %>
<div id='footer'></div>
<p id='footerParagraph'> Facultat d'Informàtica de Barcelona | Ignacio Lucero | Pol Verdaguer | Zhouyang Xue | Marc Garnica</p>
</body>
</html>